name: ipsum
favicon: null
layout_spectrum: 0.00091
typography_spectrum: 0.8768841261044145
title: lorem
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#c1b7b2'
    - '#837571'
    - '#372d3b'
    - '#5e5150'
  brandStrength: 0.22155663301236928
  lightness: 1
  saturation: 0.4062346515711397
  rhythmicContrast: 0.9846691507846117
purpose: []
