name: ipsum
favicon: null
layout_spectrum: 0.00091
typography_spectrum: 0.8768841261044145
title: lorem
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#161616'
    - '#505050'
    - '#a7a7a7'
    - '#cfcfcf'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
