name: ipsum
favicon: null
layout_spectrum: 0.00091
typography_spectrum: 0.8768841261044145
title: lorem
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#a7a7a6'
    - '#ffffff'
    - '#757265'
    - '#444130'
  brandStrength: 0.22155663301236928
  lightness: 0.48801894835196435
  saturation: 0.4062346515711397
  rhythmicContrast: 0.9846691507846117
purpose: []
