name: ipsum
favicon: null
layout_spectrum: 0.44996
typography_spectrum: 0.20718
title: lorem
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B3B4AC'
    - '#2E2721'
    - '#017788'
    - '#FB4277'
    - '#9A1FB5'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
